instructor_website/apps/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "accounts"
urlpatterns = [
    path("profile", views.ProfileView.as_view(), name="profile"),
    # Django Auth
    path(
        "login",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
]

# path('accounts/', include('django.contrib.auth.urls'))
# accounts/login/ [name='login']
# accounts/logout/ [name='logout']
# accounts/password_change/ [name='password_change']
# accounts/password_change/done/ [name='password_change_done']
# accounts/password_reset/ [name='password_reset']
# accounts/password_reset/done/ [name='password_reset_done']
# accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
# accounts/reset/done/ [name='password_reset_complete']

instructor_website/apps/contact/urls.py
from django.urls import path

from .views import contact

app_name = "contact"
urlpatterns = [path("", contact, name="contact")]

instructor_website/urls.py
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include
from django.views.generic import RedirectView

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('instructor_website.apps.public.urls')),
    path('accounts/', include('instructor_website.apps.accounts.urls')),
    path("contact/", include("instructor_website.apps.contact.urls")),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),
]

instructor_website/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class UserInterest(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name


class UserPersona(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class UserProfile(models.Model):
    # owner
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")

    # settings
    is_full_name_displayed = models.BooleanField(default=True)

    # details
    bio = models.CharField(max_length=500, blank=True, null=True)
    persona = models.ForeignKey(
        UserPersona, on_delete=models.SET_NULL, blank=True, null=True
    )
    interests = models.ManyToManyField(UserInterest, blank=True)

    # Links (TODO: Validate Input)
    website = models.URLField(max_length=200, blank=True, null=True)
    linkedin_url = models.URLField(max_length=200, blank=True, null=True)
    twitter_url = models.URLField(max_length=200, blank=True, null=True)
    youtube_url = models.URLField(max_length=200, blank=True, null=True)

instructor_website/apps/contact/models.py
from django.db import models

# Create your models here.

instructor_website/apps/contact/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Name"}),
    )
    email = forms.EmailField(
        required=True,
        widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Email"}),
    )
    message = forms.CharField(
        required=True,
        widget=forms.Textarea(
            attrs={"class": "form-control", "placeholder": "Message", "rows": 5}
        ),
    )

instructor_website/apps/accounts/views.py
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/profile.html"

instructor_website/apps/contact/views.py
import bleach
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from django.core.mail import send_mail

from instructor_website import settings

from .forms import ContactForm


def contact(request: HttpRequest) -> HttpResponse:
    if request.method == "GET":
        form = ContactForm()
    elif request.method == "POST":
        form = ContactForm(request.POST)

        if form.is_valid():
            name = bleach.clean(form.cleaned_data["name"])
            email = bleach.clean(form.cleaned_data["email"])
            message = bleach.clean(form.cleaned_data["message"])

            send_mail(
                f"{name} sent an email", message, email, [settings.DEFAULT_FROM_EMAIL]
            )

            # Use a new form to clean out the old data and render a success message
            return render(
                request, "contact.html", {"form": ContactForm(), "success": True}
            )
    else:
        raise NotImplementedError

    return render(request, "contact.html", {"form": form})

instructor_website/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')


def about(request):
    return render(request, 'about.html')


def contact(request):
    return render(request, 'contact.html')

instructor_website/templates/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block content %}
<h1>
    About Page
    <br/>
    <br/>
    <br/>

</h1>
<h5 style="text-align: center;">Fiore Games.</h5>
<!-- Add some spacing as a placeholder -->
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
{% endblock %}

instructor_website/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<h2>Login</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>
<!-- Add some spacing as a placeholder -->
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
{% endblock %}

instructor_website/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Profile{% endblock %}

{% block head %}
<link href="{% static 'css/profile.css' %}" rel="stylesheet" />
{% endblock %}

{% block content %}

{% with profile=user.profile %}
<div class="profile-page">
    <div class="page-header header-filter"></div>
    <div class="main main-raised">
		<div class="profile-content">
            <div class="container">
                <div class="row">
	                <div class="col-md-6 ml-auto mr-auto">
        	           <div class="profile">
	                        <div class="avatar">
                                <div class="box-1-1">
                                    <div class="profile-img-container img-raised img-fluid rounded-circle">
                                        <img class="masthead-avatar mb-5" src="{% static 'img/hs-logo-round.png' %}" alt="Profile picture" />
                                        <img src="http://tinygraphs.com/labs/isogrids/hexa/{{user.username}}?theme=seascape&numcolors=4&size=220&fmt=svg" alt="Profile picture">
                                    </div>
                                </div>
	                        </div>
	                        <div class="name">
	                            <h3 class="title">{{ user.get_full_name }} (@{{user.username}})</h3>
                                {% if profile %}
                                <h6>{{ profile.persona|default:"" }}</h6>
                                {% if profile.linkedin_url %}
								<a href="{{ profile.linkedin_url }}" class="btn btn-just-icon btn-link"><i class="fab fa-linkedin-in"></i></a>
                                {% endif %}
                                {% if profile.twitter_url %}
                                <a href="{{ profile.twitter_url }}" class="btn btn-just-icon btn-link"><i class="fab fa-twitter"></i></a>
                                {% endif %}
                                {% if profile.youtube_url %}
                                <a href="{{ profile.youtube_url }}" class="btn btn-just-icon btn-link"><i class="fab fa-youtube"></i></a>
                                {% endif %}
                                {% endif %}
                            </div>
	                    </div>
    	            </div>
                </div>
                {% if profile %}
                <div class="description text-center">
                    {% with website=profile.website|default:"" %}
                        <a href="{{website}}">{{ website }}</a>
                    {% endwith %}
                </div>
                <div class="description text-center">
                    Interests:
                    {% for interest in profile.interests.all %}
                        <span>
                            {{ interest.name }}{% if not forloop.last %}, {% endif %}
                        </span>
                    {% endfor %}
                </div>
                <div class="description text-center">
                    <p>{{ profile.bio|default:"" }}</p>
                </div>
                {% endif %}
                <br/>
            </div>
        </div>
	</div>
</div>
{% endwith %}
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
{% endblock %}

instructor_website/templates/base.html
{% load static %}

<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}FIORE GAMES{% endblock %}</title>

  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <!-- Font Awesome icons (free version)-->
  <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
  <!-- Google fonts-->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
  <!-- Core theme CSS (includes Bootstrap)-->
  <link href="{% static 'theme/css/styles.css' %}" rel="stylesheet" />

  <!-- Internal CSS   -->
  <link href="{% static 'css/main.css' %}" rel="stylesheet" />
  <link rel="stylesheet" href="../../static/css/profile.css">

  {% block head %}
  {% endblock %}

</head>
<body>
  {% include 'navbar.html' %}
  <main id="main">
    {% block content %}
    {% endblock %}
  </main>

  <!-- Bootstrap core JS-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
  <!-- Third party plugin JS-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
  <!-- Core theme JS-->
  <script src="{% static 'theme/js/scripts.js' %}"></script>

</body>
{% include 'footer.html' %}
</html>

instructor_website/templates/contact.html
{% extends 'base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
<section class="page-section">
    <div class="container">
        <!-- Contact Section Heading-->
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Contact Us</h2>
        <!-- Icon Divider-->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-envelope"></i></div>
            <div class="divider-custom-line"></div>
        </div>

            <div class="text-center text-secondary mb-0">
                <p>
                    We do our best to respond to emails, but we get so many that it's sometimes hard to respond to all of them. If you don't get a response, try following up in a few days. The email might be buried in our inbox.
                </p>
                <p>
                    If you need help with a anything, contact <a href="mailto:shawnpfiore1978@gmail.com">shawnpfiore1978@gmail.com</a>
                </p>
                <p>
                    You can also email us at <a href="mailto:shawnpfiore1978@gmail.com">shawnpfiore1978@gmail.com</a>
                </p>
            </div>

        <!-- Contact Section Form-->
        <div class="row">
            <div class="col-lg-8 mx-auto">

                {% if success %}
                <div class="alert alert-success" role="alert">
                    Your message was sent! Check your inbox for a response.
                </div>
                {% endif %}

                <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19.-->
                <form method="post">
                    {% csrf_token %}

                    {% if form.non_field_errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ form.non_field_errors }}
                    </div>
                    {% endif %}

                    {% for field in form %}
                    <div class="control-group">
                        <div class="form-group floating-label-form-group controls mb-0 pb-2">
                            {{ field.label_tag }}
                            {{ field }}
                            {% for error in field.errors %}
                            <p class="help-block text-danger">{{error}}</p>
                            {% endfor %}
                        </div>
                    </div>
                    {% endfor %}

                    <br />
                    <div class="form-group"><button class="btn hs-bg-primary btn-xl text-white" type="submit">Send</button></div>
                </form>
            </div>
        </div>
    </div>
</section>
<br/>
<br/>
<br/>
<br/>
<br/>
{% endblock %}

instructor_website/templates/footer.html
{% url 'public:index' as index_url %}
{% url 'public:about' as about_url %}
{% url 'contact:contact' as contact_url %}
{% url 'accounts:profile' as profile_url %} 

 <!-- Footer-->
 <footer class="footer text-center">
    <div class="container">
        <div class="row">
            <!-- Footer Location-->
            <div class="col-lg-4 mb-5 mb-lg-0">
                <p class="lead mb-0">
                    Reach Us @
                    <br/>
                    <a href="mailto:shawnpfiore1978@gmail.com">shawnpfiore1978@gmail.com</a>
                </p>
            </div>
            <!-- Footer Social Icons-->
            <div class="col-lg-4 mb-5 mb-lg-0">
                <a class="btn btn-outline-light btn-social mx-1" title="Youtube" href="https://www.youtube.com/@thelensoftruth/videos"><i class="fab fa-youtube"></i></a>
                <a class="btn btn-outline-light btn-social mx-1" title="Twitter" href="https://twitter.com/Ecsorl/"><i class="fab fa-twitter"></i></a>
                <a class="btn btn-outline-light btn-social mx-1" title="Instagram" href="https://www.linkedin.com/in/shawn-fiore//"><i class="fab fa-linkedin"></i></a>
                <!--
                <a class="btn btn-outline-light btn-social mx-1" title="Rancher" href="https://a0033ba2020464008898da1e03f749e6-1987838504.us-east-1.elb.amazonaws.com/dashboard/home//"><i class="fab fa-aws"></i></a>
                <a class="btn btn-outline-light btn-social mx-1" title="Grafana" href="https://a0033ba2020464008898da1e03f749e6-1987838504.us-east-1.elb.amazonaws.com/k8s/clusters/c-m-7xpn2kr2/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/?orgId=1//"><i class="fas fa-cloud-meatball"></i></a>
                -->

            </div>
            <!-- Footer About Text-->
            <div class="col-lg-4">
                <p class="lead mb-0 w-100">
                    Quick Links
                    <br/>
                    <a class="px-2 {% if request.path == index_url %}active{% endif %}" href="{{ index_url }}">Home</a>
                    <a class="px-2 {% if request.path == about_url %}active{% endif %}" href="{{ about_url }}">About</a>
                    <a class="px-2 {% if request.path == contact_url %}active{% endif %}" href="{{ contact_url }}">Contact</a>
                    <a class="px-2 {% if request.path == contact_url %}active{% endif %}" href="{{ index_url }}admin">Admin</a>
                </p>
            </div>
        </div>
    </div>
</footer>
<!-- Copyright Section-->
<div class="copyright py-4 text-center text-white">
    <div class="container"><small>Last Update - August 2023</small></div>
</div>
<!-- Scroll to Top Button (Only visible on small and extra-small screen sizes)-->
<div class="scroll-to-top d-lg-none position-fixed">
    <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top"><i class="fa fa-chevron-up"></i></a>
</div>

instructor_website/templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Home{% endblock %}

{% block content %}

 <!-- Masthead-->
 <header class="masthead text-white text-center">
    <div class="container d-flex align-items-center flex-column">
        <!-- Masthead Avatar Image-->
        <img class="masthead-avatar mb-5" src="{% static 'img/hs-logo-round.png' %}" alt="" />
        <!-- Masthead Heading-->
        <h1 class="masthead-heading text-uppercase mb-0">We Play Games</h1>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <!-- Masthead Heading-->
        <!-- <h1 class="masthead-heading text-uppercase mb-0">INSTRUCTOR PORTAL</h1> -->
    </div>
</header>

<!--
<h1>
    HOME PAGE
</h1>
-->

<!-- Add some spacing as a placeholder -->

{% endblock %}

instructor_website/templates/navbar.html
{% url 'public:index' as index_url %}
{% url 'public:about' as about_url %}
{% url 'contact:contact' as contact_url %}
{% url 'accounts:profile' as profile_url %}
{% url 'accounts:login' as login_url %}
{% url 'accounts:logout' as logout_url %}

<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="{{ index_url }}">FIORE GAMING</a>
        <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold hs-bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 js-scroll-trigger {% if request.path == index_url %}active{% endif %}" href="{{ index_url }}">Home</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 js-scroll-trigger {% if request.path == about_url %}active{% endif %}" href="{{ about_url }}">About</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 js-scroll-trigger {% if request.path == contact_url %}active{% endif %}" href="{{ contact_url }}">Contact</a></li>
                {% if user.is_authenticated %}
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 js-scroll-trigger {% if request.path == profile_url %}active{% endif %}" href="{{ profile_url }}">Profile</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 js-scroll-trigger {% if request.path == logout_url %}active{% endif %}" href="{{ logout_url }}">Logout</a></li>
                {% else %}
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 js-scroll-trigger {% if request.path == login_url %}active{% endif %}" href="{{ login_url }}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>